stages:
    - prepare
    - deploy

dependencies-boot:
    stage: prepare
    only:
        - main
    tags:
        - dev
    script:
        - cd boot-dependencies
        - mvn clean deploy -U -s ../settings.xml

dependencies-cloud:
    stage: prepare
    only:
        - main
    tags:
        - dev
    script:
        - cd cloud-dependencies
        - mvn clean deploy -U -s ../settings.xml

deploy-all:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - mvn install
        - mvn clean deploy -U -s settings.xml
