stages:
    - prepare
    - deploy

dependencies-boot:
    stage: prepare
    only:
        - main
    tags:
        - easykit
    script:
        - cd boot-dependencies
        - java -version
        - mvn -v
        - mvn clean deploy -U -s $CI_PROJECT_DIR/settings.xml

dependencies-cloud:
    stage: prepare
    only:
        - main
    tags:
        - easykit
    script:
        - cd cloud-dependencies
        - java -version
        - mvn -v
        - mvn clean deploy -U -s $CI_PROJECT_DIR/settings.xml

deploy-all:
    stage: deploy
    only:
        - main
    tags:
        - easykit
    script:
        - java -version
        - mvn -v
        - mvn clean deploy -U -s $CI_PROJECT_DIR/settings.xml
