stages:
    - install

install:
    stage: install
    tags:
        - dev
    script:
        - cd boot-dependencies
        - mvn install
        - cd ..
        - cd cloud-dependencies
        - mvn install
        - cd ..
        - mvn install
